export const ADD_FAVORITES = "ADD_FAVORITES";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const FILTER_BY_GENDER = "FILTER_BY_GENDER";
export const FILTER_BY_FAVS = "FILTER_BY_FAVS";
export const ORDER = "ORDER";
export const GET_FAVORITES = 'GET_FAVORITES';
export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS';